// Curated science graph for the Science Visualiser page.
//
// The graph is intentionally metadata-first. Nodes represent major concepts,
// models, or derived quantities. Edges describe how they relate in WorldSmith:
// runtime edges are backed by engine code, documented edges reflect the
// Science/Lessons reference material, and curated edges add explanatory links
// that are scientifically useful but not directly wired in code.

export const SCIENCE_GRAPH_SECTIONS = Object.freeze([
  {
    id: "cluster",
    label: "Local Cluster",
    lane: 0,
    y: 64,
    description: "Galactic environment and neighbourhood-scale inputs.",
  },
  {
    id: "stellar",
    label: "Stellar Physics",
    lane: 1,
    y: 64,
    description: "Host-star properties and activity models.",
  },
  {
    id: "system",
    label: "System Layout",
    lane: 2,
    y: 64,
    description: "Orbital context, insolation, and giant-planet likelihood.",
  },
  {
    id: "interior",
    label: "Interior & Composition",
    lane: 3,
    y: 64,
    description: "Mass, CMF, WMF, radius, density, and dynamo inputs.",
  },
  {
    id: "atmosphere",
    label: "Atmosphere & Surface",
    lane: 4,
    y: 64,
    description: "Escape, greenhouse forcing, surface temperature, and locking.",
  },
  {
    id: "moons",
    label: "Moons & Tides",
    lane: 4,
    y: 700,
    description: "Moon-driven heating and long-term orbital evolution.",
  },
  {
    id: "climate",
    label: "Climate",
    lane: 5,
    y: 64,
    description: "Liquid-water checks, circulation, and climate classification.",
  },
  {
    id: "tectonics",
    label: "Tectonics",
    lane: 5,
    y: 452,
    description: "Interior heat budget, tectonic bias, and surface regime.",
  },
  {
    id: "population",
    label: "Population",
    lane: 6,
    y: 144,
    description: "Carrying capacity and logistic growth outputs.",
  },
  {
    id: "observing",
    label: "Observing",
    lane: 6,
    y: 452,
    description: "How star and planet properties affect apparent brightness.",
  },
  {
    id: "gas_giants",
    label: "Gas Giants",
    lane: 2,
    y: 700,
    description: "Gas giant bulk properties, appearance classification, and magnetic dynamo.",
  },
  {
    id: "debris",
    label: "Debris Disks",
    lane: 1,
    y: 640,
    description: "Debris disk architecture and condensation-sequence composition.",
  },
]);

export const SCIENCE_GRAPH_NODES = Object.freeze([
  {
    id: "galactic_position",
    label: "Galactic Position",
    kind: "input",
    sectionId: "cluster",
    row: 0,
    summary:
      "Galactocentric radius and height above the Galactic plane set the mean metallicity used by the local-cluster model.",
    formula: "DeltaR and |z| shift [Fe/H] through radial and vertical metallicity gradients.",
    engineRefs: ["engine/localCluster.js"],
    docs: [
      { label: "Science - Metallicity Gradient", href: "#/science" },
      { label: "Lesson 19 - The Local Cluster", href: "#/lessons" },
    ],
    tags: ["cluster", "metallicity", "galaxy"],
  },
  {
    id: "stellar_metallicity",
    label: "Stellar Metallicity [Fe/H]",
    kind: "derived",
    sectionId: "cluster",
    row: 1,
    summary:
      "Iron abundance relative to the Sun. In WorldSmith it is generated from galactic position for cluster systems and reused by star and planet logic.",
    formula: "[Fe/H] = [Fe/H]_sun + DeltaR*g_R + |z|*g_z + delta_class + N(0, sigma)",
    engineRefs: ["engine/localCluster.js", "engine/star.js", "engine/planet.js"],
    docs: [
      { label: "Science - Metallicity Gradient", href: "#/science" },
      { label: "Lesson 19 - The Local Cluster", href: "#/lessons" },
    ],
    tags: ["cluster", "metallicity", "chemistry"],
  },
  {
    id: "stellar_mass",
    label: "Stellar Mass",
    kind: "input",
    sectionId: "stellar",
    row: 0,
    summary:
      "Master stellar input used to derive luminosity, radius, temperature, habitable-zone context, and many downstream planetary quantities.",
    formula:
      "Mass selects the mass-luminosity and mass-radius relations, or the evolved-star tracks when stellar evolution is enabled.",
    engineRefs: ["engine/star.js", "engine/system.js", "engine/planet.js"],
    docs: [
      { label: "Science - Stellar Physics", href: "#/science" },
      { label: "Lesson 01 - What Is a Star?", href: "#/lessons" },
    ],
    tags: ["star", "mass", "stellar"],
  },
  {
    id: "stellar_age",
    label: "Stellar Age",
    kind: "input",
    sectionId: "stellar",
    row: 1,
    summary:
      "Age controls evolved stellar properties, XUV history, and the stellar-activity regime used for flare and CME statistics.",
    formula: "tau = age / t_MS in the evolved-star model.",
    engineRefs: ["engine/star.js", "engine/stellarActivity.js", "engine/planet.js"],
    docs: [
      { label: "Science - Stellar Evolution", href: "#/science" },
      { label: "Lesson 04 - Stellar Evolution", href: "#/lessons" },
    ],
    tags: ["star", "age", "evolution"],
  },
  {
    id: "stellar_luminosity",
    label: "Stellar Luminosity",
    kind: "derived",
    sectionId: "stellar",
    row: 2,
    summary:
      "Radiative power output of the host star. It drives habitable-zone distances, insolation, apparent brightness, and many thermal calculations.",
    formula: "log(L/L_ZAMS) = alpha*tau + beta*tau^eta + gamma*tau^2",
    engineRefs: ["engine/star.js", "engine/system.js", "engine/planet.js", "engine/apparent.js"],
    docs: [
      { label: "Science - Stellar Physics", href: "#/science" },
      { label: "Lesson 03 - Stellar Luminosity", href: "#/lessons" },
    ],
    tags: ["star", "luminosity", "radiation"],
  },
  {
    id: "stellar_radius",
    label: "Stellar Radius",
    kind: "derived",
    sectionId: "stellar",
    row: 3,
    summary:
      "Host-star radius from the stellar model or advanced overrides. It affects apparent star size and the Stefan-Boltzmann temperature solution.",
    formula: "L = R^2 * (T/5776)^4 in solar-normalised form.",
    engineRefs: ["engine/star.js", "engine/apparent.js"],
    docs: [
      { label: "Science - Stellar Physics", href: "#/science" },
      { label: "Lesson 01 - What Is a Star?", href: "#/lessons" },
    ],
    tags: ["star", "radius", "observing"],
  },
  {
    id: "stellar_temperature",
    label: "Stellar Temperature",
    kind: "derived",
    sectionId: "stellar",
    row: 4,
    summary:
      "Effective temperature of the host star. It sets spectral class, habitable-zone Seff corrections, colour, and several atmospheric colour lookups.",
    formula: "T_eff = (L / R^2)^0.25 * 5776 K",
    engineRefs: ["engine/star.js", "engine/system.js", "engine/planet.js"],
    docs: [
      { label: "Science - Stellar Physics", href: "#/science" },
      { label: "Lesson 02 - Classifying Stars", href: "#/lessons" },
    ],
    tags: ["star", "temperature", "spectral"],
  },
  {
    id: "stellar_activity",
    label: "Stellar Activity",
    kind: "model",
    sectionId: "stellar",
    row: 5,
    summary:
      "Flare and CME occurrence model derived from spectral-type bins, age bands, and cycle phase. It is not yet a direct planet-habitability input, but it is documented science context in the project.",
    formula: "Rates depend on N32, alpha, and cycle modulation in the activity model.",
    engineRefs: ["engine/stellarActivity.js"],
    docs: [
      { label: "Science - Stellar Activity", href: "#/science" },
      { label: "Lesson 15 - Stellar Activity", href: "#/lessons" },
    ],
    tags: ["star", "activity", "flares"],
  },
  {
    id: "habitable_zone",
    label: "Habitable Zone",
    kind: "derived",
    sectionId: "system",
    row: 0,
    summary:
      "Temperature-dependent Kopparapu-style habitable-zone bounds derived from stellar luminosity and temperature.",
    formula: "d = sqrt(L / S_eff)",
    engineRefs: ["engine/star.js", "engine/system.js"],
    docs: [
      { label: "Science - Stellar Physics", href: "#/science" },
      { label: "Lesson 05 - The Habitable Zone", href: "#/lessons" },
    ],
    tags: ["system", "habitability", "orbit"],
  },
  {
    id: "giant_planet_probability",
    label: "Giant Planet Probability",
    kind: "derived",
    sectionId: "system",
    row: 1,
    summary:
      "Probability that a star hosts a giant planet, estimated from stellar metallicity. This is a direct star-model output and a useful bridge between stellar chemistry and system architecture.",
    formula:
      "P = clamp(0.07 * M * 10^(2*[Fe/H]), 0, 1). M is stellar mass in Msol (defaults to 1 in cluster view).",
    engineRefs: ["engine/star.js", "ui/localClusterPage.js"],
    docs: [
      { label: "Science - Stellar Physics", href: "#/science" },
      { label: "Lesson 19 - The Local Cluster", href: "#/lessons" },
    ],
    tags: ["system", "metallicity", "giants"],
  },
  {
    id: "planet_orbit",
    label: "Planet Orbit",
    kind: "input",
    sectionId: "system",
    row: 2,
    summary:
      "Semi-major axis and orbital geometry place the planet within the system, setting insolation, period, seasonal context, and tidal-lock timescales.",
    formula: "P^2 = a^3 / M_* in years and AU for Keplerian orbits.",
    engineRefs: ["engine/system.js", "engine/planet.js", "engine/apparent.js"],
    docs: [
      { label: "Science - Orbital Mechanics", href: "#/science" },
      { label: "Lesson 06 - Orbital Mechanics", href: "#/lessons" },
    ],
    tags: ["system", "orbit", "kepler"],
  },
  {
    id: "planet_rotation",
    label: "Planet Rotation",
    kind: "input",
    sectionId: "system",
    row: 3,
    summary:
      "Rotation period controls circulation-cell count and contributes to tidal-lock behaviour and magnetic-field morphology.",
    formula: "WorldSmith bins circulation into 1, 3, 5, or 7-cell regimes from rotation period.",
    engineRefs: ["engine/planet.js"],
    docs: [
      { label: "Science - Climate Classification", href: "#/science" },
      { label: "Lesson 14 - Climate Zones", href: "#/lessons" },
    ],
    tags: ["rotation", "climate", "planet"],
  },
  {
    id: "planet_insolation",
    label: "Planet Insolation",
    kind: "derived",
    sectionId: "system",
    row: 4,
    summary:
      "Incident stellar power at the planet's orbit. It is the cleanest bridge between the stellar model and planetary temperature.",
    formula: "S = L / a^2 in Earth-normalised units.",
    engineRefs: ["engine/planet.js"],
    docs: [
      { label: "Science - Planetary Physics", href: "#/science" },
      { label: "Lesson 10 - Surface Temperature", href: "#/lessons" },
    ],
    tags: ["insolation", "orbit", "temperature"],
  },
  {
    id: "planet_mass",
    label: "Planet Mass",
    kind: "input",
    sectionId: "interior",
    row: 0,
    summary:
      "Primary planetary bulk input. Mass feeds radius and density, escape velocity, tectonic bias, and atmospheric retention.",
    formula:
      "Mass enters empirical rocky-planet and gas-giant scaling relations throughout the engine.",
    engineRefs: ["engine/planet.js", "engine/gasGiant.js", "engine/tectonics.js"],
    docs: [
      { label: "Science - Planetary Physics", href: "#/science" },
      { label: "Lesson 07 - Rocky Planets", href: "#/lessons" },
    ],
    tags: ["planet", "mass", "bulk"],
  },
  {
    id: "suggested_cmf",
    label: "Suggested CMF",
    kind: "derived",
    sectionId: "interior",
    row: 1,
    summary:
      "Rocky-core fraction inferred from stellar metallicity before the user overrides it. It is the clearest chemistry-to-interior bridge in the current project.",
    formula: "Suggested CMF rises with [Fe/H] and is clamped to plausible rocky-planet bounds.",
    engineRefs: ["engine/planet.js"],
    docs: [
      { label: "Science - Planetary Interiors", href: "#/science" },
      { label: "Lesson 08 - Interiors and Density", href: "#/lessons" },
    ],
    tags: ["cmf", "metallicity", "interior"],
  },
  {
    id: "planet_cmf",
    label: "Planet CMF",
    kind: "input",
    sectionId: "interior",
    row: 2,
    summary:
      "Core mass fraction used by the rocky-planet solver. It changes density, magnetic scaling, and tectonic tendencies.",
    formula: "CMF = M_core / M_planet",
    engineRefs: ["engine/planet.js", "engine/tectonics.js"],
    docs: [
      { label: "Science - Planetary Interiors", href: "#/science" },
      { label: "Lesson 08 - Interiors and Density", href: "#/lessons" },
    ],
    tags: ["cmf", "core", "interior"],
  },
  {
    id: "planet_wmf",
    label: "Planet WMF",
    kind: "input",
    sectionId: "interior",
    row: 3,
    summary:
      "Water mass fraction used in the rocky-planet structure model and later climate and tectonic heuristics.",
    formula: "WMF = M_water / M_planet",
    engineRefs: ["engine/planet.js", "engine/climate.js", "engine/tectonics.js"],
    docs: [
      { label: "Science - Planetary Interiors", href: "#/science" },
      { label: "Lesson 08 - Interiors and Density", href: "#/lessons" },
    ],
    tags: ["wmf", "water", "interior"],
  },
  {
    id: "radius_density",
    label: "Radius and Density",
    kind: "derived",
    sectionId: "interior",
    row: 4,
    summary:
      "Bulk structure solution from mass, CMF, and WMF. It is one of the highest-leverage nodes in the planetary pipeline.",
    formula: "R = f(M, CMF, WMF), rho = M / (4*pi*R^3/3)",
    engineRefs: ["engine/planet.js"],
    docs: [
      { label: "Science - Density and Radius", href: "#/science" },
      { label: "Lesson 08 - Interiors and Density", href: "#/lessons" },
    ],
    tags: ["radius", "density", "structure"],
  },
  {
    id: "gravity_escape",
    label: "Gravity and Escape Velocity",
    kind: "derived",
    sectionId: "interior",
    row: 5,
    summary:
      "Surface gravity and escape velocity derived from mass and radius. These feed atmospheric retention and several surface heuristics.",
    formula: "g = M / R^2, v_escape = sqrt(2GM/R)",
    engineRefs: ["engine/planet.js", "engine/tectonics.js"],
    docs: [
      { label: "Science - Planetary Physics", href: "#/science" },
      { label: "Lesson 07 - Rocky Planets", href: "#/lessons" },
    ],
    tags: ["gravity", "escape", "structure"],
  },
  {
    id: "magnetic_field",
    label: "Magnetic Field",
    kind: "derived",
    sectionId: "interior",
    row: 6,
    summary:
      "Dipole-strength estimate based on core size, density, heat budget, and rotation-related assumptions.",
    formula: "B ~ core_factor * density_factor * heat_factor",
    engineRefs: ["engine/planet.js"],
    docs: [
      { label: "Science - Magnetospheres", href: "#/science" },
      { label: "Lesson 13 - Magnetic Fields", href: "#/lessons" },
    ],
    tags: ["magnetic", "dynamo", "core"],
  },
  {
    id: "radioisotopes",
    label: "Radioisotope Abundance",
    kind: "input",
    sectionId: "interior",
    row: 7,
    summary: "Long-lived internal heat source used in core-cooling and tectonic heuristics.",
    formula: "Radiogenic heating is treated as a scalar abundance factor in the current engine.",
    engineRefs: ["engine/planet.js", "engine/tectonics.js"],
    docs: [
      { label: "Science - Planetary Interiors", href: "#/science" },
      { label: "Lesson 16 - Plate Tectonics", href: "#/lessons" },
    ],
    tags: ["radiogenic", "heat", "interior"],
  },
  {
    id: "atmospheric_escape",
    label: "Atmospheric Escape",
    kind: "model",
    sectionId: "atmosphere",
    row: 0,
    summary:
      "Loss tendency from Jeans escape and related retention heuristics. It links gravity and stellar environment to long-term atmosphere survival.",
    formula: "Retention depends on v_escape, exobase temperature, and molecular mass.",
    engineRefs: ["engine/planet.js", "engine/gasGiant.js"],
    docs: [
      { label: "Science - Atmospheres", href: "#/science" },
      { label: "Lesson 09 - Atmospheres", href: "#/lessons" },
    ],
    tags: ["atmosphere", "escape", "loss"],
  },
  {
    id: "greenhouse",
    label: "Greenhouse Effect",
    kind: "model",
    sectionId: "atmosphere",
    row: 1,
    summary:
      "Optical-depth-based greenhouse forcing from atmospheric pressure and gas mix. This is the main atmosphere-to-temperature bridge in the rocky-planet path.",
    formula: "tau = f(P, gas_mix), DeltaT = f(tau)",
    engineRefs: ["engine/planet.js"],
    docs: [
      { label: "Science - Atmospheres", href: "#/science" },
      { label: "Lesson 10 - Surface Temperature", href: "#/lessons" },
    ],
    tags: ["atmosphere", "greenhouse", "temperature"],
  },
  {
    id: "surface_temperature",
    label: "Surface Temperature",
    kind: "derived",
    sectionId: "atmosphere",
    row: 2,
    summary:
      "Mean equilibrium-plus-greenhouse surface temperature used throughout climate and water-state checks.",
    formula: "T_surface = f(S, albedo, greenhouse)",
    engineRefs: ["engine/planet.js", "engine/tectonics.js"],
    docs: [
      { label: "Science - Surface Temperature", href: "#/science" },
      { label: "Lesson 10 - Surface Temperature", href: "#/lessons" },
    ],
    tags: ["surface", "temperature", "climate"],
  },
  {
    id: "tidal_lock",
    label: "Tidal Lock State",
    kind: "derived",
    sectionId: "atmosphere",
    row: 3,
    summary:
      "Synchronous or near-synchronous rotation state estimated from orbital distance and star-planet geometry. It switches climate behaviour on the climate page.",
    formula: "Lock likelihood increases strongly for close-in orbits and older systems.",
    engineRefs: ["engine/planet.js", "engine/climate.js"],
    docs: [
      { label: "Science - Tides", href: "#/science" },
      { label: "Lesson 12 - Moons and Tides", href: "#/lessons" },
    ],
    tags: ["tides", "rotation", "climate"],
  },
  {
    id: "moon_tides",
    label: "Moon Tidal Heating",
    kind: "derived",
    sectionId: "moons",
    row: 0,
    summary:
      "Heating generated within moons by orbital eccentricity and tidal flexing. WorldSmith also aggregates moon-driven heating back into the parent planet's tidal budget.",
    formula: "dE/dt ~ e^2 * M_p^(5/2) * R_m^5 / a^(15/2)",
    engineRefs: ["engine/moon.js", "engine/planet.js"],
    docs: [
      { label: "Science - Tides", href: "#/science" },
      { label: "Lesson 12 - Moons and Tides", href: "#/lessons" },
    ],
    tags: ["moons", "tides", "heating"],
  },
  {
    id: "planet_tidal_heating",
    label: "Planet Tidal Heating",
    kind: "derived",
    sectionId: "moons",
    row: 1,
    summary:
      "Aggregate heating term imported into tectonic and magnetic heuristics from star-planet or moon-planet tides.",
    formula: "Tidal heating is treated as a scalar budget term in downstream models.",
    engineRefs: ["engine/planet.js", "engine/tectonics.js"],
    docs: [
      { label: "Science - Tides", href: "#/science" },
      { label: "Lesson 12 - Moons and Tides", href: "#/lessons" },
    ],
    tags: ["tides", "heating", "planet"],
  },
  {
    id: "orbital_recession",
    label: "Orbital Recession",
    kind: "derived",
    sectionId: "moons",
    row: 2,
    summary:
      "Long-term change in moon semi-major axis from tidal exchange between planetary spin and orbital motion.",
    formula: "da/dt = f(k2/Q, spin, a, M_m, M_p, R_p)",
    engineRefs: ["engine/moon.js"],
    docs: [
      { label: "Science - Tides", href: "#/science" },
      { label: "Lesson 12 - Moons and Tides", href: "#/lessons" },
    ],
    tags: ["moons", "orbital", "tides"],
  },
  {
    id: "liquid_water",
    label: "Liquid Water Window",
    kind: "classifier",
    sectionId: "climate",
    row: 0,
    summary:
      "Whether the current pressure-temperature state can support stable liquid water at the surface.",
    formula:
      "Liquid water requires appropriate T_surface and pressure relative to phase boundaries.",
    engineRefs: ["engine/planet.js", "engine/climate.js"],
    docs: [
      { label: "Science - Water and Climate", href: "#/science" },
      { label: "Lesson 11 - Water Worlds", href: "#/lessons" },
    ],
    tags: ["water", "habitability", "surface"],
  },
  {
    id: "circulation_cells",
    label: "Circulation Cells",
    kind: "classifier",
    sectionId: "climate",
    row: 1,
    summary:
      "Coarse atmospheric circulation regime selected mainly from rotation period. It feeds the climate-zone model and visualisation.",
    formula: "Rotation bins map to 1, 3, 5, or 7-cell circulation.",
    engineRefs: ["engine/planet.js", "engine/climate.js"],
    docs: [
      { label: "Science - Climate Classification", href: "#/science" },
      { label: "Lesson 14 - Climate Zones", href: "#/lessons" },
    ],
    tags: ["circulation", "rotation", "climate"],
  },
  {
    id: "climate_zones",
    label: "Climate Zones",
    kind: "derived",
    sectionId: "climate",
    row: 2,
    summary:
      "Latitude-band climate result from surface temperature, pressure, rotation, tilt proxies, and water state. This is the main climate output reused by the population page.",
    formula: "Zones are assigned from thermal gradients, circulation, and hydrology heuristics.",
    engineRefs: ["engine/climate.js", "ui/climatePage.js", "ui/populationPage.js"],
    docs: [
      { label: "Science - Climate Classification", href: "#/science" },
      { label: "Lesson 14 - Climate Zones", href: "#/lessons" },
    ],
    tags: ["climate", "zones", "surface"],
  },
  {
    id: "tectonic_regime",
    label: "Tectonic Regime",
    kind: "classifier",
    sectionId: "tectonics",
    row: 0,
    summary:
      "Probabilistic tectonic outcome informed by mass, water, core fraction, heat budget, age, and tidal heating.",
    formula: "Regime weights are built from tectonic bias terms and normalised to probabilities.",
    engineRefs: ["engine/planet.js", "engine/tectonics.js", "ui/tectonicsPage.js"],
    docs: [
      { label: "Science - Plate Tectonics", href: "#/science" },
      { label: "Lesson 16 - Plate Tectonics", href: "#/lessons" },
    ],
    tags: ["tectonics", "regime", "surface"],
  },
  {
    id: "carrying_capacity",
    label: "Carrying Capacity",
    kind: "derived",
    sectionId: "population",
    row: 0,
    summary:
      "Population support estimate derived from climate-zone livability, water availability, and planet size.",
    formula: "K = area_factor * habitability_factor * technology and policy modifiers",
    engineRefs: ["engine/population.js", "ui/populationPage.js"],
    docs: [
      { label: "Science - Population", href: "#/science" },
      { label: "Lesson 18 - Population", href: "#/lessons" },
    ],
    tags: ["population", "capacity", "habitability"],
  },
  {
    id: "current_population",
    label: "Current Population",
    kind: "derived",
    sectionId: "population",
    row: 1,
    summary:
      "Logistic-growth population estimate built on top of carrying capacity and elapsed settlement time.",
    formula: "P(t) = K / (1 + A*e^(-rt))",
    engineRefs: ["engine/population.js", "ui/populationPage.js"],
    docs: [
      { label: "Science - Population", href: "#/science" },
      { label: "Lesson 18 - Population", href: "#/lessons" },
    ],
    tags: ["population", "logistic", "civilization"],
  },
  {
    id: "apparent_brightness",
    label: "Apparent Brightness",
    kind: "derived",
    sectionId: "observing",
    row: 0,
    summary:
      "Observer-facing brightness and angular-size outputs derived from the star, planet orbit, and viewing geometry.",
    formula: "Brightness follows reflected-light phase geometry and stellar flux scaling.",
    engineRefs: ["engine/apparent.js"],
    docs: [
      { label: "Science - Apparent Sky", href: "#/science" },
      { label: "Lesson 17 - The Sky", href: "#/lessons" },
    ],
    tags: ["observing", "brightness", "apparent"],
  },
  {
    id: "angular_size",
    label: "Angular Size",
    kind: "derived",
    sectionId: "observing",
    row: 1,
    summary:
      "Apparent angular diameter of the host star, moons, and neighbouring planets as seen from the world's surface.",
    formula: "theta = 2R / d in radians, converted to arcseconds or arcminutes for display.",
    engineRefs: ["engine/apparent.js"],
    docs: [
      { label: "Science - Apparent Sky", href: "#/science" },
      { label: "Lesson 17 - The Sky", href: "#/lessons" },
    ],
    tags: ["observing", "angular", "size"],
  },
  {
    id: "spectral_class",
    label: "Spectral Class",
    kind: "classifier",
    sectionId: "stellar",
    row: 6,
    summary:
      "OBAFGKM classification derived from effective temperature. It selects stellar-activity bins and provides a familiar labelling system.",
    formula: "Temperature ranges map to spectral subtypes (e.g. G2V for ~5770 K).",
    engineRefs: ["engine/star.js"],
    docs: [
      { label: "Science - Stellar Physics", href: "#/science" },
      { label: "Lesson 02 - Classifying Stars", href: "#/lessons" },
    ],
    tags: ["star", "spectral", "classification"],
  },
  {
    id: "frost_line",
    label: "Frost Line",
    kind: "derived",
    sectionId: "system",
    row: 5,
    summary:
      "The snow line beyond which water ice condenses in the protoplanetary disk. It separates rocky-planet and giant-planet formation zones.",
    formula: "a_frost = 4.85 * sqrt(L_sol) AU.",
    engineRefs: ["engine/system.js", "engine/debrisDisk.js"],
    docs: [
      { label: "Science - System Architecture", href: "#/science" },
      { label: "Lesson 06 - Orbital Mechanics", href: "#/lessons" },
    ],
    tags: ["system", "frost", "ice"],
  },
  {
    id: "axial_tilt",
    label: "Axial Tilt",
    kind: "input",
    sectionId: "system",
    row: 6,
    summary:
      "Obliquity of the planet's spin axis relative to its orbital plane. It drives seasonal temperature amplitude in the climate model.",
    formula: "Seasonal amplitude scales as sin(lat) * (tilt / 23.44).",
    engineRefs: ["engine/planet.js", "engine/climate.js"],
    docs: [
      { label: "Science - Climate Classification", href: "#/science" },
      { label: "Lesson 14 - Climate Zones", href: "#/lessons" },
    ],
    tags: ["tilt", "obliquity", "seasons"],
  },
  {
    id: "orbital_eccentricity",
    label: "Orbital Eccentricity",
    kind: "input",
    sectionId: "system",
    row: 7,
    summary:
      "Deviation of the orbit from circular. Higher eccentricity increases tidal heating and modulates seasonal insolation variation.",
    formula: "Tidal heating scales with the Wisdom eccentricity function f(e) ~ e^2 / (1-e^2)^7.5.",
    engineRefs: ["engine/planet.js", "engine/moon.js"],
    docs: [
      { label: "Science - Orbital Mechanics", href: "#/science" },
      { label: "Lesson 06 - Orbital Mechanics", href: "#/lessons" },
    ],
    tags: ["eccentricity", "orbit", "tides"],
  },
  {
    id: "surface_pressure",
    label: "Surface Pressure",
    kind: "input",
    sectionId: "atmosphere",
    row: 4,
    summary:
      "Total atmospheric pressure at the surface. It controls greenhouse optical depth, Rayleigh-scattering sky colour, atmospheric-tide torque, and climate gradient damping.",
    formula: "Greenhouse forcing scales as f_GH = 1 + factor * P^0.25.",
    engineRefs: ["engine/planet.js", "engine/climate.js"],
    docs: [
      { label: "Science - Atmospheres", href: "#/science" },
      { label: "Lesson 09 - Atmospheres", href: "#/lessons" },
    ],
    tags: ["pressure", "atmosphere", "surface"],
  },
  {
    id: "atmospheric_composition",
    label: "Atmospheric Composition",
    kind: "input",
    sectionId: "atmosphere",
    row: 5,
    summary:
      "Gas mix (N2, O2, CO2, Ar, other) expressed as partial fractions. It sets greenhouse species, mean molecular weight for Jeans escape, and sky-colour tinting.",
    formula: "Partial pressures P_i = P_total * frac_i / 100; mean molecular weight from mix.",
    engineRefs: ["engine/planet.js"],
    docs: [
      { label: "Science - Atmospheres", href: "#/science" },
      { label: "Lesson 09 - Atmospheres", href: "#/lessons" },
    ],
    tags: ["composition", "gas", "atmosphere"],
  },
  {
    id: "albedo",
    label: "Bond Albedo",
    kind: "derived",
    sectionId: "atmosphere",
    row: 6,
    summary:
      "Fraction of incident stellar energy reflected by the planet. It directly reduces absorbed flux in the equilibrium-temperature calculation.",
    formula: "T_eq^4 = L(1-a) / (16*pi*sigma*d^2).",
    engineRefs: ["engine/planet.js"],
    docs: [
      { label: "Science - Surface Temperature", href: "#/science" },
      { label: "Lesson 10 - Surface Temperature", href: "#/lessons" },
    ],
    tags: ["albedo", "reflection", "energy"],
  },
  {
    id: "sky_colour",
    label: "Sky Colour",
    kind: "derived",
    sectionId: "atmosphere",
    row: 7,
    summary:
      "Apparent daytime sky hue computed from stellar temperature, surface pressure, gravity, and CO2 fraction using OKLab interpolation.",
    formula: "Lookup from stellar T_eff and effective column depth P*sqrt(g), with CO2 tint.",
    engineRefs: ["engine/planet.js"],
    docs: [
      { label: "Science - Atmospheres", href: "#/science" },
      { label: "Lesson 09 - Atmospheres", href: "#/lessons" },
    ],
    tags: ["sky", "colour", "rayleigh"],
  },
  {
    id: "moon_surface_temp",
    label: "Moon Surface Temperature",
    kind: "derived",
    sectionId: "moons",
    row: 3,
    summary:
      "Combined surface temperature from stellar equilibrium heating, tidal dissipation, and radiogenic heat sources.",
    formula: "T_surf^4 = T_eq^4 + T_tidal^4 + T_rad^4.",
    engineRefs: ["engine/moon.js"],
    docs: [
      { label: "Science - Moons", href: "#/science" },
      { label: "Lesson 12 - Moons and Tides", href: "#/lessons" },
    ],
    tags: ["moon", "temperature", "surface"],
  },
  {
    id: "moon_volatiles",
    label: "Moon Volatiles",
    kind: "derived",
    sectionId: "moons",
    row: 4,
    summary:
      "Per-species volatile inventory (N2, CO, CH4, H2O, CO2, NH3, SO2) from sublimation state, Jeans retention, and volcanic resupply.",
    formula: "Species present if density allows; retained if Jeans lambda > 6 and tau_esc > age.",
    engineRefs: ["engine/moon.js"],
    docs: [
      { label: "Science - Moons", href: "#/science" },
      { label: "Lesson 12 - Moons and Tides", href: "#/lessons" },
    ],
    tags: ["moon", "volatiles", "atmosphere"],
  },
  {
    id: "water_regime",
    label: "Water Regime",
    kind: "classifier",
    sectionId: "climate",
    row: 3,
    summary:
      "Surface water coverage classification (Dry, Shallow, Extensive, Global, Deep, Ice) from water mass fraction and thermal state.",
    formula: "WMF and surface temperature select the water-coverage label.",
    engineRefs: ["engine/planet.js", "engine/climate.js"],
    docs: [
      { label: "Science - Water and Climate", href: "#/science" },
      { label: "Lesson 11 - Water Worlds", href: "#/lessons" },
    ],
    tags: ["water", "ocean", "regime"],
  },
  {
    id: "climate_state",
    label: "Climate State",
    kind: "classifier",
    sectionId: "climate",
    row: 4,
    summary:
      "Extreme climate regime flag: snowball, moist greenhouse, or runaway greenhouse. " +
      "Uses surface temperature and absorbed stellar flux against threshold values.",
    formula:
      "absorbed = S \u00d7 1361 \u00d7 (1 \u2212 A) / 4; thresholds: 282 W/m\u00b2, 340 K, 240 K",
    engineRefs: ["engine/planet.js"],
    docs: [{ label: "Lesson 10 \u2014 Surface Temperature", href: "#/lessons" }],
    tags: ["climate", "greenhouse", "snowball", "habitability"],
  },
  {
    id: "volcanic_activity",
    label: "Volcanic Activity",
    kind: "derived",
    sectionId: "tectonics",
    row: 1,
    summary:
      "Interior heat-driven volcanic intensity from radiogenic decay, tidal heating, and planetary age. It modulates topographic features and atmospheric resupply.",
    formula: "Activity = exp(-0.15 * age / abundance) + tidal boost.",
    engineRefs: ["engine/tectonics.js"],
    docs: [
      { label: "Science - Plate Tectonics", href: "#/science" },
      { label: "Lesson 16 - Plate Tectonics", href: "#/lessons" },
    ],
    tags: ["volcanic", "activity", "heat"],
  },
  {
    id: "mountain_height",
    label: "Peak Height Limit",
    kind: "derived",
    sectionId: "tectonics",
    row: 2,
    summary:
      "Maximum mountain peak height set by surface gravity and crustal yield stress. Higher gravity worlds have lower peak limits.",
    formula: "H_max = C / g, where C depends on crustal composition (9267 m for Earth-like).",
    engineRefs: ["engine/tectonics.js"],
    docs: [
      { label: "Science - Plate Tectonics", href: "#/science" },
      { label: "Lesson 16 - Plate Tectonics", href: "#/lessons" },
    ],
    tags: ["mountain", "gravity", "topography"],
  },
  {
    id: "ocean_depth",
    label: "Ocean Depth",
    kind: "derived",
    sectionId: "tectonics",
    row: 3,
    summary:
      "Abyssal ocean depth from the Parsons-Sclater plate-cooling model. Younger oceanic crust is shallower; older crust reaches ~6400 m.",
    formula: "d = ridge + 350*sqrt(age_Myr) for young crust; plate-model asymptote for old crust.",
    engineRefs: ["engine/tectonics.js"],
    docs: [
      { label: "Science - Plate Tectonics", href: "#/science" },
      { label: "Lesson 16 - Plate Tectonics", href: "#/lessons" },
    ],
    tags: ["ocean", "depth", "plate"],
  },
  {
    id: "erosion_rate",
    label: "Erosion Rate",
    kind: "derived",
    sectionId: "tectonics",
    row: 4,
    summary:
      "Climate-adjusted surface erosion intensity from temperature and moisture factors. It controls long-term topographic smoothing.",
    formula: "Rate = 5 * tempFactor * moistureFactor m/Myr.",
    engineRefs: ["engine/tectonics.js"],
    docs: [
      { label: "Science - Plate Tectonics", href: "#/science" },
      { label: "Lesson 16 - Plate Tectonics", href: "#/lessons" },
    ],
    tags: ["erosion", "weathering", "climate"],
  },
  {
    id: "land_area",
    label: "Habitable Land Area",
    kind: "derived",
    sectionId: "population",
    row: 2,
    summary:
      "Total habitable land derived from planet radius, ocean fraction, and climate-zone livability in the population land-use cascade.",
    formula: "Land = surface_area * (1 - ocean_fraction) * habitability_factor.",
    engineRefs: ["engine/population.js"],
    docs: [
      { label: "Science - Population", href: "#/science" },
      { label: "Lesson 18 - Population", href: "#/lessons" },
    ],
    tags: ["land", "area", "habitable"],
  },
  {
    id: "gas_giant_structure",
    label: "Gas Giant Structure",
    kind: "model",
    sectionId: "gas_giants",
    row: 0,
    summary:
      "Mass-radius-density solution for gas giants from Chen and Kipping (2017) forecaster relations, plus atmospheric metallicity from stellar [Fe/H].",
    formula: "R/R_J follows piecewise power laws with transition near ~0.4 M_J.",
    engineRefs: ["engine/gasGiant.js"],
    docs: [
      { label: "Science - Gas Giants", href: "#/science" },
      { label: "Lesson 07 - Rocky Planets", href: "#/lessons" },
    ],
    tags: ["giant", "mass", "radius"],
  },
  {
    id: "gas_giant_appearance",
    label: "Appearance Class",
    kind: "classifier",
    sectionId: "gas_giants",
    row: 1,
    summary:
      "Sudarsky class I-V from equilibrium cloud-top temperature. It determines dominant cloud species (NH3, H2S, silicate) and visual colour.",
    formula: "Temperature thresholds select class I (ammonia) through V (thermal emission).",
    engineRefs: ["engine/gasGiant.js"],
    docs: [
      { label: "Science - Gas Giants", href: "#/science" },
      { label: "Lesson 07 - Rocky Planets", href: "#/lessons" },
    ],
    tags: ["giant", "sudarsky", "clouds"],
  },
  {
    id: "gas_giant_dynamo",
    label: "Gas Giant Dynamo",
    kind: "model",
    sectionId: "gas_giants",
    row: 2,
    summary:
      "Magnetic dipole strength from Christensen et al. (2009) energy-flux scaling, self-normalised to Jupiter's field.",
    formula: "B ~ (rho * q_conv * R)^(1/3), normalised to B_J = 4.28 G.",
    engineRefs: ["engine/gasGiant.js"],
    docs: [
      { label: "Science - Gas Giants", href: "#/science" },
      { label: "Lesson 13 - Magnetic Fields", href: "#/lessons" },
    ],
    tags: ["giant", "magnetic", "dynamo"],
  },
  {
    id: "disk_architecture",
    label: "Disk Architecture",
    kind: "derived",
    sectionId: "debris",
    row: 0,
    summary:
      "Belt positions from mean-motion resonance zones of giant planets, or frost-line fallback when no giants are present.",
    formula: "a_res = a_giant * (p/q)^(2/3) for priority-ranked MMR slots.",
    engineRefs: ["engine/debrisDisk.js"],
    docs: [
      { label: "Science - Debris Disks", href: "#/science" },
      { label: "Lesson 06 - Orbital Mechanics", href: "#/lessons" },
    ],
    tags: ["debris", "resonance", "belts"],
  },
  {
    id: "disk_composition",
    label: "Disk Composition",
    kind: "derived",
    sectionId: "debris",
    row: 1,
    summary:
      "Species inventory from the Lodders (2003) condensation sequence scaled by stellar metallicity. It determines refractory-to-volatile ratios across the disk.",
    formula: "13-species condensation table with metallicity scaling: f_ref ~ [Fe/H]^0.25.",
    engineRefs: ["engine/debrisDisk.js"],
    docs: [
      { label: "Science - Debris Disks", href: "#/science" },
      { label: "Lesson 06 - Orbital Mechanics", href: "#/lessons" },
    ],
    tags: ["debris", "composition", "condensation"],
  },
]);

export const SCIENCE_GRAPH_EDGES = Object.freeze([
  {
    sourceId: "galactic_position",
    targetId: "stellar_metallicity",
    evidence: "runtime",
    relationship: "drives",
    summary: "Local-cluster position sets the baseline metallicity distribution.",
    engineRefs: ["engine/localCluster.js"],
  },
  {
    sourceId: "stellar_metallicity",
    targetId: "giant_planet_probability",
    evidence: "runtime",
    relationship: "drives",
    summary: "Higher metallicity increases the estimated occurrence of giant planets.",
    engineRefs: ["engine/star.js"],
  },
  {
    sourceId: "stellar_mass",
    targetId: "giant_planet_probability",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Higher-mass stars host giant planets more frequently (Johnson et al. 2010).",
    engineRefs: ["engine/star.js"],
  },
  {
    sourceId: "stellar_metallicity",
    targetId: "suggested_cmf",
    evidence: "runtime",
    relationship: "drives",
    summary: "Rocky-planet CMF defaults are nudged upward or downward by stellar metallicity.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "stellar_mass",
    targetId: "stellar_luminosity",
    evidence: "runtime",
    relationship: "drives",
    summary: "Mass is the leading term in the stellar luminosity fit.",
    engineRefs: ["engine/star.js"],
  },
  {
    sourceId: "stellar_mass",
    targetId: "stellar_radius",
    evidence: "runtime",
    relationship: "drives",
    summary: "Mass selects the star-radius relation used by the stellar solver.",
    engineRefs: ["engine/star.js"],
  },
  {
    sourceId: "stellar_mass",
    targetId: "stellar_temperature",
    evidence: "runtime",
    relationship: "drives",
    summary: "Temperature follows from the luminosity-radius solution selected by mass.",
    engineRefs: ["engine/star.js"],
  },
  {
    sourceId: "stellar_age",
    targetId: "stellar_luminosity",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Age changes luminosity through the evolved-star track.",
    engineRefs: ["engine/star.js"],
  },
  {
    sourceId: "stellar_age",
    targetId: "stellar_radius",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Age changes radius when stellar evolution is enabled.",
    engineRefs: ["engine/star.js"],
  },
  {
    sourceId: "stellar_age",
    targetId: "stellar_activity",
    evidence: "runtime",
    relationship: "drives",
    summary: "Activity rate bins depend strongly on age.",
    engineRefs: ["engine/stellarActivity.js"],
  },
  {
    sourceId: "stellar_luminosity",
    targetId: "habitable_zone",
    evidence: "runtime",
    relationship: "drives",
    summary: "Habitable-zone distances scale with stellar luminosity.",
    engineRefs: ["engine/star.js"],
  },
  {
    sourceId: "stellar_temperature",
    targetId: "habitable_zone",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Temperature shifts the effective stellar flux used by HZ bounds.",
    engineRefs: ["engine/star.js"],
  },
  {
    sourceId: "stellar_luminosity",
    targetId: "planet_insolation",
    evidence: "runtime",
    relationship: "drives",
    summary: "Brighter stars deliver more flux at a fixed orbit.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "planet_orbit",
    targetId: "planet_insolation",
    evidence: "runtime",
    relationship: "drives",
    summary: "Orbital distance sets the inverse-square dilution of stellar flux.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "planet_orbit",
    targetId: "tidal_lock",
    evidence: "runtime",
    relationship: "drives",
    summary: "Close orbits increase the chance of synchronous rotation.",
    engineRefs: ["engine/planet.js", "engine/climate.js"],
  },
  {
    sourceId: "planet_rotation",
    targetId: "circulation_cells",
    evidence: "runtime",
    relationship: "classifies",
    summary: "Rotation period is binned into a circulation-cell regime.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "planet_mass",
    targetId: "radius_density",
    evidence: "runtime",
    relationship: "drives",
    summary: "Bulk mass is the main term in the structure solution.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "suggested_cmf",
    targetId: "planet_cmf",
    evidence: "runtime",
    relationship: "drives",
    summary: "Suggested CMF becomes the active rocky-planet CMF unless overridden.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "planet_cmf",
    targetId: "radius_density",
    evidence: "runtime",
    relationship: "drives",
    summary: "Higher CMF makes a rocky planet denser and usually smaller at fixed mass.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "planet_wmf",
    targetId: "radius_density",
    evidence: "runtime",
    relationship: "drives",
    summary: "Higher WMF shifts the structure solution toward lower density and larger radius.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "radius_density",
    targetId: "gravity_escape",
    evidence: "runtime",
    relationship: "drives",
    summary: "Radius and density determine gravity and escape velocity.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "planet_cmf",
    targetId: "magnetic_field",
    evidence: "runtime",
    relationship: "drives",
    summary: "Core fraction affects dynamo scaling through core size.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "radius_density",
    targetId: "magnetic_field",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Density and radius feed magnetic scaling terms.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "planet_tidal_heating",
    targetId: "magnetic_field",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Tidal heat contributes to the convective heat budget used by the dynamo proxy.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "radioisotopes",
    targetId: "magnetic_field",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Radiogenic heat helps sustain the convective energy available to the core.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "gravity_escape",
    targetId: "atmospheric_escape",
    evidence: "runtime",
    relationship: "drives",
    summary: "Higher escape velocity improves volatile retention.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "stellar_activity",
    targetId: "atmospheric_escape",
    evidence: "curated",
    relationship: "modulates",
    summary:
      "Higher XUV and flare activity should stress atmospheric retention, even where not wired directly yet.",
    engineRefs: ["engine/stellarActivity.js", "engine/planet.js"],
  },
  {
    sourceId: "atmospheric_escape",
    targetId: "greenhouse",
    evidence: "runtime",
    relationship: "modulates",
    summary:
      "Atmospheric survival influences the pressure and gas inventory available to greenhouse forcing.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "planet_insolation",
    targetId: "surface_temperature",
    evidence: "runtime",
    relationship: "drives",
    summary: "Insolation is the dominant external heating term for surface temperature.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "greenhouse",
    targetId: "surface_temperature",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Greenhouse forcing raises the equilibrium surface temperature.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "surface_temperature",
    targetId: "liquid_water",
    evidence: "runtime",
    relationship: "classifies",
    summary: "Surface temperature is checked against water-phase boundaries.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "habitable_zone",
    targetId: "liquid_water",
    evidence: "documented",
    relationship: "constrains",
    summary:
      "Habitable-zone placement is reference context for where liquid water becomes more plausible.",
    engineRefs: ["engine/star.js"],
  },
  {
    sourceId: "planet_rotation",
    targetId: "tidal_lock",
    evidence: "curated",
    relationship: "modulates",
    summary:
      "Rotation state interacts with the lock-timescale story even if the current project treats lock status more directly.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "liquid_water",
    targetId: "climate_zones",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Water availability changes the climate-zone heuristics and map outputs.",
    engineRefs: ["engine/climate.js"],
  },
  {
    sourceId: "surface_temperature",
    targetId: "climate_zones",
    evidence: "runtime",
    relationship: "drives",
    summary: "Climate zones are built on top of the planet's thermal state.",
    engineRefs: ["engine/climate.js"],
  },
  {
    sourceId: "circulation_cells",
    targetId: "climate_zones",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Circulation regime affects climate-band structure.",
    engineRefs: ["engine/climate.js"],
  },
  {
    sourceId: "tidal_lock",
    targetId: "climate_zones",
    evidence: "runtime",
    relationship: "modulates",
    summary: "A locked planet uses an alternate climate path.",
    engineRefs: ["engine/climate.js"],
  },

  // ── Climate state ──
  {
    sourceId: "surface_temperature",
    targetId: "climate_state",
    evidence: "runtime",
    relationship: "classifies",
    summary:
      "Surface temperature checked against snowball (< 240 K) and moist greenhouse (> 340 K) thresholds.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "albedo",
    targetId: "climate_state",
    evidence: "runtime",
    relationship: "modulates",
    summary:
      "Bond albedo determines the absorbed fraction of incident flux for the runaway greenhouse check.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "planet_insolation",
    targetId: "climate_state",
    evidence: "runtime",
    relationship: "drives",
    summary: "Insolation sets the incident stellar flux used in the absorbed-flux diagnostic.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "water_regime",
    targetId: "climate_state",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Dry worlds are always Stable; snowball and greenhouse states require surface water.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "climate_state",
    targetId: "climate_zones",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Climate state feeds advisory warnings into the climate-zone output.",
    engineRefs: ["engine/climate.js"],
  },

  {
    sourceId: "moon_tides",
    targetId: "planet_tidal_heating",
    evidence: "runtime",
    relationship: "drives",
    summary: "Moon-system tides feed the planetary tidal-heating budget.",
    engineRefs: ["engine/moon.js", "engine/planet.js"],
  },
  {
    sourceId: "moon_tides",
    targetId: "orbital_recession",
    evidence: "runtime",
    relationship: "drives",
    summary: "Tidal exchange also produces long-term moon-orbit recession.",
    engineRefs: ["engine/moon.js"],
  },
  {
    sourceId: "planet_mass",
    targetId: "tectonic_regime",
    evidence: "runtime",
    relationship: "drives",
    summary: "Mass influences tectonic probability biases and tectonic output intensity.",
    engineRefs: ["engine/planet.js", "engine/tectonics.js"],
  },
  {
    sourceId: "planet_cmf",
    targetId: "tectonic_regime",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Core fraction contributes to tectonic-bias and interior-structure terms.",
    engineRefs: ["engine/planet.js", "engine/tectonics.js"],
  },
  {
    sourceId: "planet_wmf",
    targetId: "tectonic_regime",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Water inventory shifts tectonic style and subduction likelihood.",
    engineRefs: ["engine/planet.js", "engine/tectonics.js"],
  },
  {
    sourceId: "planet_tidal_heating",
    targetId: "tectonic_regime",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Tidal heating adds to the active internal heat budget.",
    engineRefs: ["engine/planet.js", "engine/tectonics.js"],
  },
  {
    sourceId: "radioisotopes",
    targetId: "tectonic_regime",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Radiogenic heating supports tectonic longevity.",
    engineRefs: ["engine/planet.js", "engine/tectonics.js"],
  },
  {
    sourceId: "surface_temperature",
    targetId: "tectonic_regime",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Surface conditions are included in the tectonics output model.",
    engineRefs: ["engine/tectonics.js"],
  },
  {
    sourceId: "radius_density",
    targetId: "carrying_capacity",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Planet size affects total habitable area and carrying capacity.",
    engineRefs: ["engine/population.js"],
  },
  {
    sourceId: "climate_zones",
    targetId: "carrying_capacity",
    evidence: "runtime",
    relationship: "drives",
    summary: "Climate-zone livability is one of the direct inputs to carrying capacity.",
    engineRefs: ["engine/population.js"],
  },
  {
    sourceId: "liquid_water",
    targetId: "carrying_capacity",
    evidence: "documented",
    relationship: "constrains",
    summary: "Stable liquid water is a core prerequisite in the population science framing.",
    engineRefs: ["engine/population.js"],
  },
  {
    sourceId: "carrying_capacity",
    targetId: "current_population",
    evidence: "runtime",
    relationship: "drives",
    summary: "Population is evolved toward carrying capacity using logistic growth.",
    engineRefs: ["engine/population.js"],
  },
  {
    sourceId: "stellar_luminosity",
    targetId: "apparent_brightness",
    evidence: "runtime",
    relationship: "drives",
    summary: "Stellar luminosity sets the baseline brightness of the host star.",
    engineRefs: ["engine/apparent.js"],
  },
  {
    sourceId: "stellar_radius",
    targetId: "apparent_brightness",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Stellar radius contributes to angular size and illumination geometry.",
    engineRefs: ["engine/apparent.js"],
  },
  {
    sourceId: "planet_orbit",
    targetId: "apparent_brightness",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Orbital distance affects reflected-light brightness and apparent star size.",
    engineRefs: ["engine/apparent.js"],
  },
  {
    sourceId: "radius_density",
    targetId: "apparent_brightness",
    evidence: "curated",
    relationship: "modulates",
    summary:
      "Planetary radius affects reflected-light brightness even though the graph groups radius and density together.",
    engineRefs: ["engine/apparent.js", "engine/planet.js"],
  },

  // ── Spectral class ──
  {
    sourceId: "stellar_temperature",
    targetId: "spectral_class",
    evidence: "runtime",
    relationship: "classifies",
    summary: "Temperature ranges map directly to OBAFGKM spectral subtypes.",
    engineRefs: ["engine/star.js"],
  },
  {
    sourceId: "spectral_class",
    targetId: "stellar_activity",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Activity-rate bins are keyed by spectral type (FGK, early-M, late-M).",
    engineRefs: ["engine/stellarActivity.js"],
  },

  // ── Frost line ──
  {
    sourceId: "stellar_luminosity",
    targetId: "frost_line",
    evidence: "runtime",
    relationship: "drives",
    summary: "The snow line scales as a_frost = 4.85 * sqrt(L).",
    engineRefs: ["engine/system.js"],
  },

  // ── Axial tilt ──
  {
    sourceId: "axial_tilt",
    targetId: "climate_zones",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Obliquity drives seasonal temperature amplitude across latitude bands.",
    engineRefs: ["engine/climate.js"],
  },

  // ── Orbital eccentricity ──
  {
    sourceId: "orbital_eccentricity",
    targetId: "planet_tidal_heating",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Star-planet tidal heating depends on the Wisdom eccentricity function f(e).",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "orbital_eccentricity",
    targetId: "climate_zones",
    evidence: "curated",
    relationship: "modulates",
    summary: "Eccentricity variations modulate seasonal insolation even at fixed semi-major axis.",
    engineRefs: ["engine/planet.js"],
  },

  // ── Surface pressure ──
  {
    sourceId: "surface_pressure",
    targetId: "greenhouse",
    evidence: "runtime",
    relationship: "drives",
    summary: "Pressure sets the optical depth used in greenhouse forcing.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "surface_pressure",
    targetId: "atmospheric_escape",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Surface pressure appears in the escape-timescale denominator.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "surface_pressure",
    targetId: "tidal_lock",
    evidence: "runtime",
    relationship: "modulates",
    summary:
      "Atmospheric thermal-tide torque scales with pressure and can prevent synchronous lock.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "surface_pressure",
    targetId: "sky_colour",
    evidence: "runtime",
    relationship: "drives",
    summary: "Rayleigh scattering depth is controlled by surface pressure and gravity.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "surface_pressure",
    targetId: "climate_zones",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Pressure damps the equator-pole temperature gradient in the climate model.",
    engineRefs: ["engine/climate.js"],
  },

  // ── Atmospheric composition ──
  {
    sourceId: "atmospheric_composition",
    targetId: "greenhouse",
    evidence: "runtime",
    relationship: "drives",
    summary: "Gas mix determines which greenhouse species are present and their forcing.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "atmospheric_composition",
    targetId: "atmospheric_escape",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Mean molecular mass from the gas mix affects the Jeans escape parameter.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "atmospheric_composition",
    targetId: "sky_colour",
    evidence: "runtime",
    relationship: "drives",
    summary: "CO2 fraction applies a tint correction to the sky-colour lookup.",
    engineRefs: ["engine/planet.js"],
  },

  // ── Albedo ──
  {
    sourceId: "albedo",
    targetId: "surface_temperature",
    evidence: "runtime",
    relationship: "drives",
    summary: "Albedo reduces absorbed stellar flux in the equilibrium temperature formula.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "surface_pressure",
    targetId: "albedo",
    evidence: "curated",
    relationship: "modulates",
    summary:
      "Pressure and cloud formation affect planetary reflectivity even where not directly coupled.",
    engineRefs: ["engine/planet.js"],
  },

  // ── Sky colour ──
  {
    sourceId: "stellar_temperature",
    targetId: "sky_colour",
    evidence: "runtime",
    relationship: "drives",
    summary: "Star spectral type sets the illuminant colour for the sky-colour lookup.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "gravity_escape",
    targetId: "sky_colour",
    evidence: "runtime",
    relationship: "modulates",
    summary:
      "Surface gravity affects the effective atmospheric column depth for Rayleigh scattering.",
    engineRefs: ["engine/planet.js"],
  },

  // ── Moon surface temperature ──
  {
    sourceId: "planet_insolation",
    targetId: "moon_surface_temp",
    evidence: "runtime",
    relationship: "drives",
    summary: "Moons receive stellar flux at the parent planet's orbital distance.",
    engineRefs: ["engine/moon.js"],
  },
  {
    sourceId: "moon_tides",
    targetId: "moon_surface_temp",
    evidence: "runtime",
    relationship: "drives",
    summary: "Tidal dissipation adds a T_tidal^4 heating term to moon surface temperature.",
    engineRefs: ["engine/moon.js"],
  },
  {
    sourceId: "radioisotopes",
    targetId: "moon_surface_temp",
    evidence: "documented",
    relationship: "modulates",
    summary: "Radiogenic heating from the moon interior contributes a baseline heat source.",
    engineRefs: ["engine/moon.js"],
  },

  // ── Moon volatiles ──
  {
    sourceId: "moon_surface_temp",
    targetId: "moon_volatiles",
    evidence: "runtime",
    relationship: "classifies",
    summary: "Temperature determines which volatile ices sublimate into a thin atmosphere.",
    engineRefs: ["engine/moon.js"],
  },
  {
    sourceId: "moon_tides",
    targetId: "moon_volatiles",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Tidally driven volcanism resupplies SO2 even when Jeans escape is active.",
    engineRefs: ["engine/moon.js"],
  },

  // ── Water regime ──
  {
    sourceId: "planet_wmf",
    targetId: "water_regime",
    evidence: "runtime",
    relationship: "drives",
    summary: "Water mass fraction is the primary determinant of ocean coverage.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "surface_temperature",
    targetId: "water_regime",
    evidence: "runtime",
    relationship: "classifies",
    summary: "Temperature determines whether water is liquid, ice, or vapour at the surface.",
    engineRefs: ["engine/planet.js"],
  },
  {
    sourceId: "water_regime",
    targetId: "climate_zones",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Ocean coverage directly affects the moisture index in climate-zone assignment.",
    engineRefs: ["engine/climate.js"],
  },
  {
    sourceId: "water_regime",
    targetId: "land_area",
    evidence: "runtime",
    relationship: "drives",
    summary: "Ocean fraction determines the land fraction available for population.",
    engineRefs: ["engine/population.js"],
  },

  // ── Volcanic activity ──
  {
    sourceId: "radioisotopes",
    targetId: "volcanic_activity",
    evidence: "runtime",
    relationship: "drives",
    summary: "Radiogenic decay is the primary long-lived heat source driving volcanism.",
    engineRefs: ["engine/tectonics.js"],
  },
  {
    sourceId: "planet_tidal_heating",
    targetId: "volcanic_activity",
    evidence: "runtime",
    relationship: "drives",
    summary: "Tidal heating supplements radiogenic heat in the volcanic activity budget.",
    engineRefs: ["engine/tectonics.js"],
  },
  {
    sourceId: "stellar_age",
    targetId: "volcanic_activity",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Radiogenic decay reduces volcanic intensity exponentially with age.",
    engineRefs: ["engine/tectonics.js"],
  },

  // ── Peak height limit ──
  {
    sourceId: "gravity_escape",
    targetId: "mountain_height",
    evidence: "runtime",
    relationship: "drives",
    summary: "Surface gravity is the dominant limiter of maximum mountain peak height.",
    engineRefs: ["engine/tectonics.js"],
  },
  {
    sourceId: "tectonic_regime",
    targetId: "mountain_height",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Tectonic style determines convergence rate and mountain-building potential.",
    engineRefs: ["engine/tectonics.js"],
  },
  {
    sourceId: "volcanic_activity",
    targetId: "mountain_height",
    evidence: "documented",
    relationship: "modulates",
    summary: "Volcanic shields can exceed plate-boundary peaks on stagnant-lid worlds.",
    engineRefs: ["engine/tectonics.js"],
  },

  // ── Ocean depth ──
  {
    sourceId: "stellar_age",
    targetId: "ocean_depth",
    evidence: "runtime",
    relationship: "drives",
    summary: "Oceanic plate age determines depth via the Parsons-Sclater cooling model.",
    engineRefs: ["engine/tectonics.js"],
  },
  {
    sourceId: "tectonic_regime",
    targetId: "ocean_depth",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Spreading rate affects seafloor age distribution and mean depth.",
    engineRefs: ["engine/tectonics.js"],
  },

  // ── Erosion rate ──
  {
    sourceId: "surface_temperature",
    targetId: "erosion_rate",
    evidence: "runtime",
    relationship: "drives",
    summary: "Temperature controls chemical weathering intensity.",
    engineRefs: ["engine/tectonics.js"],
  },
  {
    sourceId: "climate_zones",
    targetId: "erosion_rate",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Moisture from climate zones drives physical and chemical erosion rates.",
    engineRefs: ["engine/tectonics.js"],
  },

  // ── Habitable land area ──
  {
    sourceId: "radius_density",
    targetId: "land_area",
    evidence: "runtime",
    relationship: "drives",
    summary: "Planet radius sets total surface area in the land-use cascade.",
    engineRefs: ["engine/population.js"],
  },
  {
    sourceId: "land_area",
    targetId: "carrying_capacity",
    evidence: "runtime",
    relationship: "drives",
    summary: "Habitable land area is the primary spatial input to carrying capacity.",
    engineRefs: ["engine/population.js"],
  },

  // ── Angular size ──
  {
    sourceId: "stellar_radius",
    targetId: "angular_size",
    evidence: "runtime",
    relationship: "drives",
    summary: "Star angular diameter is proportional to stellar radius.",
    engineRefs: ["engine/apparent.js"],
  },
  {
    sourceId: "planet_orbit",
    targetId: "angular_size",
    evidence: "runtime",
    relationship: "drives",
    summary: "Distance from star to planet sets the angular size of the host star.",
    engineRefs: ["engine/apparent.js"],
  },
  {
    sourceId: "radius_density",
    targetId: "angular_size",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Body radius affects the angular size of moons and planets in the sky.",
    engineRefs: ["engine/apparent.js"],
  },

  // ── Gas giant structure ──
  {
    sourceId: "giant_planet_probability",
    targetId: "gas_giant_structure",
    evidence: "documented",
    relationship: "drives",
    summary: "Metallicity-driven occurrence probability is context for whether gas giants form.",
    engineRefs: ["engine/star.js", "engine/gasGiant.js"],
  },
  {
    sourceId: "frost_line",
    targetId: "gas_giant_structure",
    evidence: "documented",
    relationship: "modulates",
    summary: "Core accretion occurs preferentially beyond the snow line.",
    engineRefs: ["engine/system.js", "engine/gasGiant.js"],
  },
  {
    sourceId: "stellar_metallicity",
    targetId: "gas_giant_structure",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Stellar metallicity sets the default atmospheric metallicity for gas giants.",
    engineRefs: ["engine/gasGiant.js"],
  },

  // ── Gas giant appearance ──
  {
    sourceId: "gas_giant_structure",
    targetId: "gas_giant_appearance",
    evidence: "runtime",
    relationship: "drives",
    summary: "Equilibrium temperature from mass and orbit determines the Sudarsky class.",
    engineRefs: ["engine/gasGiant.js"],
  },
  {
    sourceId: "stellar_luminosity",
    targetId: "gas_giant_appearance",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Stellar flux determines cloud-top temperature and hence appearance class.",
    engineRefs: ["engine/gasGiant.js"],
  },

  // ── Gas giant dynamo ──
  {
    sourceId: "gas_giant_structure",
    targetId: "gas_giant_dynamo",
    evidence: "runtime",
    relationship: "drives",
    summary: "Christensen energy-flux scaling uses mass, radius, density, and convective heat.",
    engineRefs: ["engine/gasGiant.js"],
  },

  // ── Disk architecture ──
  {
    sourceId: "gas_giant_structure",
    targetId: "disk_architecture",
    evidence: "runtime",
    relationship: "drives",
    summary: "Giant-planet orbital positions set mean-motion resonance zones for debris belts.",
    engineRefs: ["engine/debrisDisk.js"],
  },
  {
    sourceId: "frost_line",
    targetId: "disk_architecture",
    evidence: "runtime",
    relationship: "drives",
    summary: "When no giants exist the frost line sets fallback belt positions.",
    engineRefs: ["engine/debrisDisk.js"],
  },

  // ── Disk composition ──
  {
    sourceId: "stellar_luminosity",
    targetId: "disk_composition",
    evidence: "runtime",
    relationship: "drives",
    summary: "Temperature profile from stellar luminosity sets condensation-front positions.",
    engineRefs: ["engine/debrisDisk.js"],
  },
  {
    sourceId: "stellar_metallicity",
    targetId: "disk_composition",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Metallicity scales refractory and volatile mass fractions in the disk.",
    engineRefs: ["engine/debrisDisk.js"],
  },
  {
    sourceId: "disk_composition",
    targetId: "suggested_cmf",
    evidence: "documented",
    relationship: "modulates",
    summary:
      "Disk refractory-to-volatile ratios inform the rocky planet composition that CMF approximates.",
    engineRefs: ["engine/planet.js", "engine/debrisDisk.js"],
  },

  // ── Missing edges for existing nodes ──
  {
    sourceId: "stellar_age",
    targetId: "tectonic_regime",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Planetary age governs radiogenic decay and tectonic longevity.",
    engineRefs: ["engine/tectonics.js"],
  },
  {
    sourceId: "stellar_mass",
    targetId: "tidal_lock",
    evidence: "runtime",
    relationship: "modulates",
    summary: "Star mass appears squared in the tidal-lock timescale denominator.",
    engineRefs: ["engine/planet.js"],
  },
]);
