const GREGORIAN_DAY_NAMES = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
];

const GREGORIAN_MONTH_NAMES = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

// Base "month-shape" rules map the engine's uniform solar month model
// to Gregorian month lengths; leap rules then correct February.
const GREGORIAN_LEAP_RULES = [
  {
    id: "leap-greg-shape-jan",
    name: "Gregorian month shape: January",
    cycleYears: 1,
    offsetYear: 1,
    monthIndex: 0,
    dayDelta: 1,
  },
  {
    id: "leap-greg-shape-feb",
    name: "Gregorian month shape: February",
    cycleYears: 1,
    offsetYear: 1,
    monthIndex: 1,
    dayDelta: -2,
  },
  {
    id: "leap-greg-shape-mar",
    name: "Gregorian month shape: March",
    cycleYears: 1,
    offsetYear: 1,
    monthIndex: 2,
    dayDelta: 1,
  },
  {
    id: "leap-greg-shape-may",
    name: "Gregorian month shape: May",
    cycleYears: 1,
    offsetYear: 1,
    monthIndex: 4,
    dayDelta: 1,
  },
  {
    id: "leap-greg-shape-jul",
    name: "Gregorian month shape: July",
    cycleYears: 1,
    offsetYear: 1,
    monthIndex: 6,
    dayDelta: 1,
  },
  {
    id: "leap-greg-shape-aug",
    name: "Gregorian month shape: August",
    cycleYears: 1,
    offsetYear: 1,
    monthIndex: 7,
    dayDelta: 1,
  },
  {
    id: "leap-greg-shape-oct",
    name: "Gregorian month shape: October",
    cycleYears: 1,
    offsetYear: 1,
    monthIndex: 9,
    dayDelta: 1,
  },
  {
    id: "leap-greg-shape-dec",
    name: "Gregorian month shape: December",
    cycleYears: 1,
    offsetYear: 1,
    monthIndex: 11,
    dayDelta: -4,
  },
  {
    id: "leap-greg-4",
    name: "Gregorian leap year (+1 day in February every 4 years)",
    cycleYears: 4,
    offsetYear: 4,
    monthIndex: 1,
    dayDelta: 1,
  },
  {
    id: "leap-greg-100",
    name: "Gregorian century correction (-1 day in February every 100 years)",
    cycleYears: 100,
    offsetYear: 100,
    monthIndex: 1,
    dayDelta: -1,
  },
  {
    id: "leap-greg-400",
    name: "Gregorian 400-year correction (+1 day in February every 400 years)",
    cycleYears: 400,
    offsetYear: 400,
    monthIndex: 1,
    dayDelta: 1,
  },
];

const UK_SUBSTITUTE_OBSERVANCE = {
  weekendRule: "next-weekday",
  holidayConflictRule: "next-weekday",
  maxShiftDays: 7,
  stayInMonth: false,
};

const UK_CONFLICT_SCOPE_ALL = {
  appliesAgainst: "all",
  categories: [],
  holidayIds: [],
};

const UK_HOLIDAY_RULES = [
  {
    id: "holiday-new-year",
    name: "New Year's Day",
    category: "civic",
    colorTag: "gold",
    recurrence: "yearly",
    startMonth: 0,
    year: 1,
    attrs: { useDate: true, useWeekday: false, useMoonPhase: false },
    anchor: {
      type: "fixed-date",
      algorithmKey: "none",
      moonSlot: 0,
      moonId: "",
      moonPhase: "F",
      markerKey: "",
      holidayId: "",
    },
    offsetDays: 0,
    observance: UK_SUBSTITUTE_OBSERVANCE,
    conflictScope: UK_CONFLICT_SCOPE_ALL,
    dayOfMonth: 1,
    durationDays: 1,
    priority: 5,
    mergeMode: "merge",
  },
  {
    id: "holiday-good-friday",
    name: "Good Friday",
    category: "religious",
    colorTag: "violet",
    recurrence: "yearly",
    startMonth: 0,
    year: 1,
    attrs: { useDate: true, useWeekday: false, useMoonPhase: false },
    anchor: {
      type: "algorithmic",
      algorithmKey: "gregorian-easter-western",
      moonSlot: 0,
      moonId: "",
      moonPhase: "F",
      markerKey: "",
      holidayId: "",
    },
    offsetDays: -2,
    observance: {
      weekendRule: "none",
      holidayConflictRule: "merge",
      maxShiftDays: 7,
      stayInMonth: false,
    },
    conflictScope: UK_CONFLICT_SCOPE_ALL,
    dayOfMonth: 1,
    durationDays: 1,
    priority: 6,
    mergeMode: "merge",
  },
  {
    id: "holiday-easter-sunday",
    name: "Easter Sunday",
    category: "religious",
    colorTag: "violet",
    recurrence: "yearly",
    startMonth: 0,
    year: 1,
    attrs: { useDate: true, useWeekday: false, useMoonPhase: false },
    anchor: {
      type: "algorithmic",
      algorithmKey: "gregorian-easter-western",
      moonSlot: 0,
      moonId: "",
      moonPhase: "F",
      markerKey: "",
      holidayId: "",
    },
    offsetDays: 0,
    observance: {
      weekendRule: "none",
      holidayConflictRule: "merge",
      maxShiftDays: 7,
      stayInMonth: false,
    },
    conflictScope: UK_CONFLICT_SCOPE_ALL,
    dayOfMonth: 1,
    durationDays: 1,
    priority: 7,
    mergeMode: "merge",
  },
  {
    id: "holiday-easter-monday",
    name: "Easter Monday",
    category: "religious",
    colorTag: "violet",
    recurrence: "yearly",
    startMonth: 0,
    year: 1,
    attrs: { useDate: true, useWeekday: false, useMoonPhase: false },
    anchor: {
      type: "algorithmic",
      algorithmKey: "gregorian-easter-western",
      moonSlot: 0,
      moonId: "",
      moonPhase: "F",
      markerKey: "",
      holidayId: "",
    },
    offsetDays: 1,
    observance: {
      weekendRule: "none",
      holidayConflictRule: "merge",
      maxShiftDays: 7,
      stayInMonth: false,
    },
    conflictScope: UK_CONFLICT_SCOPE_ALL,
    dayOfMonth: 1,
    durationDays: 1,
    priority: 6,
    mergeMode: "merge",
  },
  {
    id: "holiday-early-may-bank",
    name: "Early May Bank Holiday",
    category: "civic",
    colorTag: "azure",
    recurrence: "yearly",
    startMonth: 4,
    attrs: { useDate: false, useWeekday: true, useMoonPhase: false },
    anchor: {
      type: "nth-weekday",
      algorithmKey: "none",
      moonSlot: 0,
      moonId: "",
      moonPhase: "F",
      markerKey: "",
      holidayId: "",
    },
    offsetDays: 0,
    observance: {
      weekendRule: "none",
      holidayConflictRule: "merge",
      maxShiftDays: 7,
      stayInMonth: false,
    },
    conflictScope: UK_CONFLICT_SCOPE_ALL,
    weekday: 0,
    occurrence: "1",
    durationDays: 1,
    priority: 4,
    mergeMode: "merge",
  },
  {
    id: "holiday-spring-bank",
    name: "Spring Bank Holiday",
    category: "civic",
    colorTag: "azure",
    recurrence: "yearly",
    startMonth: 4,
    attrs: { useDate: false, useWeekday: true, useMoonPhase: false },
    anchor: {
      type: "nth-weekday",
      algorithmKey: "none",
      moonSlot: 0,
      moonId: "",
      moonPhase: "F",
      markerKey: "",
      holidayId: "",
    },
    offsetDays: 0,
    observance: {
      weekendRule: "none",
      holidayConflictRule: "merge",
      maxShiftDays: 7,
      stayInMonth: false,
    },
    conflictScope: UK_CONFLICT_SCOPE_ALL,
    weekday: 0,
    occurrence: "last",
    durationDays: 1,
    priority: 4,
    mergeMode: "merge",
  },
  {
    id: "holiday-summer-bank",
    name: "Summer Bank Holiday",
    category: "civic",
    colorTag: "azure",
    recurrence: "yearly",
    startMonth: 7,
    attrs: { useDate: false, useWeekday: true, useMoonPhase: false },
    anchor: {
      type: "nth-weekday",
      algorithmKey: "none",
      moonSlot: 0,
      moonId: "",
      moonPhase: "F",
      markerKey: "",
      holidayId: "",
    },
    offsetDays: 0,
    observance: {
      weekendRule: "none",
      holidayConflictRule: "merge",
      maxShiftDays: 7,
      stayInMonth: false,
    },
    conflictScope: UK_CONFLICT_SCOPE_ALL,
    weekday: 0,
    occurrence: "last",
    durationDays: 1,
    priority: 4,
    mergeMode: "merge",
  },
  {
    id: "holiday-christmas-day",
    name: "Christmas Day",
    category: "religious",
    colorTag: "gold",
    recurrence: "yearly",
    startMonth: 11,
    attrs: { useDate: true, useWeekday: false, useMoonPhase: false },
    anchor: {
      type: "fixed-date",
      algorithmKey: "none",
      moonSlot: 0,
      moonId: "",
      moonPhase: "F",
      markerKey: "",
      holidayId: "",
    },
    offsetDays: 0,
    observance: UK_SUBSTITUTE_OBSERVANCE,
    conflictScope: UK_CONFLICT_SCOPE_ALL,
    dayOfMonth: 25,
    durationDays: 1,
    priority: 7,
    mergeMode: "merge",
  },
  {
    id: "holiday-boxing-day",
    name: "Boxing Day",
    category: "civic",
    colorTag: "emerald",
    recurrence: "yearly",
    startMonth: 11,
    attrs: { useDate: true, useWeekday: false, useMoonPhase: false },
    anchor: {
      type: "fixed-date",
      algorithmKey: "none",
      moonSlot: 0,
      moonId: "",
      moonPhase: "F",
      markerKey: "",
      holidayId: "",
    },
    offsetDays: 0,
    observance: UK_SUBSTITUTE_OBSERVANCE,
    conflictScope: UK_CONFLICT_SCOPE_ALL,
    dayOfMonth: 26,
    durationDays: 1,
    priority: 5,
    mergeMode: "merge",
  },
];

const SOL_PRESET_WORLD = {
  version: 51,
  selectedBodyType: "planet",
  star: {
    name: "Sol",
    massMsol: 1.0,
    ageGyr: 4.603,
    radiusRsolOverride: null,
    luminosityLsolOverride: null,
    tempKOverride: null,
    metallicityFeH: 0.0,
    physicsMode: "simple",
    advancedDerivationMode: "rl",
    evolutionMode: "zams",
    activityModelVersion: "v2",
  },
  system: {
    orbitMode: "manual",
    spacingFactor: 0.3,
    orbit1Au: 0.39,
    gasGiants: {
      selectedId: "gg_jupiter",
      order: ["gg_jupiter", "gg_saturn", "gg_uranus", "gg_neptune"],
      byId: {
        gg_jupiter: {
          id: "gg_jupiter",
          name: "Jupiter",
          au: 5.2026,
          slotIndex: null,
          style: "jupiter",
          rings: false,
          radiusRj: 1.0,
          massMjup: 1.0,
          rotationPeriodHours: 9.925,
          metallicity: 4.5,
        },
        gg_saturn: {
          id: "gg_saturn",
          name: "Saturn",
          au: 9.5549,
          slotIndex: null,
          style: "jupiter",
          rings: true,
          radiusRj: 0.862,
          massMjup: 0.299,
          rotationPeriodHours: 10.656,
          metallicity: 10,
        },
        gg_uranus: {
          id: "gg_uranus",
          name: "Uranus",
          au: 19.218,
          slotIndex: null,
          style: "neptune",
          rings: false,
          radiusRj: 0.366,
          massMjup: 0.0457,
          rotationPeriodHours: 17.24,
          metallicity: 80,
        },
        gg_neptune: {
          id: "gg_neptune",
          name: "Neptune",
          au: 30.11,
          slotIndex: null,
          style: "neptune",
          rings: false,
          radiusRj: 0.354,
          massMjup: 0.054,
          rotationPeriodHours: 16.11,
          metallicity: 80,
        },
      },
    },
    debrisDisks: {
      order: ["dd1", "dd2"],
      byId: {
        dd1: {
          id: "dd1",
          name: "Kuiper belt",
          innerAu: 39.4,
          outerAu: 47.8,
          suggested: false,
          eccentricity: 0.05,
          inclination: null,
          totalMassMearth: null,
        },
        dd2: {
          id: "dd2",
          name: "Asteroid belt",
          innerAu: 2.06,
          outerAu: 3.27,
          suggested: false,
          eccentricity: 0.1,
          inclination: null,
          totalMassMearth: null,
        },
      },
    },
  },
  planets: {
    selectedId: "p_earth",
    order: ["p_mercury", "p_venus", "p_earth", "p_ceres", "p_mars", "p_pluto"],
    byId: {
      p_mercury: {
        id: "p_mercury",
        name: "Mercury",
        slotIndex: null,
        locked: false,
        inputs: {
          name: "Mercury",
          semiMajorAxisAu: 0.3871,
          eccentricity: 0.2056,
          inclinationDeg: 7.005,
          longitudeOfPeriapsisDeg: 77.46,
          subsolarLongitudeDeg: 0.0,
          rotationPeriodHours: 1407.6,
          axialTiltDeg: 0.034,
          massEarth: 0.0553,
          cmfPct: 70.0,
          wmfPct: 0,
          albedoBond: 0.068,
          greenhouseEffect: 0.0,
          greenhouseMode: "core",
          observerHeightM: 1.75,
          pressureAtm: 0.0,
          o2Pct: 0.0,
          co2Pct: 0.0,
          arPct: 0.0,
          h2oPct: 0,
          ch4Pct: 0,
          h2Pct: 0,
          hePct: 0,
          so2Pct: 0,
          nh3Pct: 0,
          tectonicRegime: "stagnant",
          mantleOxidation: "earth",
        },
      },
      p_venus: {
        id: "p_venus",
        name: "Venus",
        slotIndex: null,
        locked: false,
        inputs: {
          name: "Venus",
          semiMajorAxisAu: 0.7233,
          eccentricity: 0.0068,
          inclinationDeg: 3.395,
          longitudeOfPeriapsisDeg: 131.53,
          subsolarLongitudeDeg: 0.0,
          rotationPeriodHours: 5832.6,
          axialTiltDeg: 177.36,
          massEarth: 0.815,
          cmfPct: 31.17,
          wmfPct: 0,
          albedoBond: 0.77,
          greenhouseEffect: 217.0,
          greenhouseMode: "core",
          observerHeightM: 1.75,
          pressureAtm: 92.0,
          o2Pct: 0.0,
          co2Pct: 96.5,
          arPct: 0.007,
          h2oPct: 0.003,
          ch4Pct: 0,
          h2Pct: 0,
          hePct: 0.0012,
          so2Pct: 0.015,
          nh3Pct: 0,
          tectonicRegime: "stagnant",
          mantleOxidation: "earth",
        },
      },
      p_earth: {
        id: "p_earth",
        name: "Earth",
        slotIndex: null,
        locked: false,
        inputs: {
          name: "Earth",
          semiMajorAxisAu: 1.0,
          eccentricity: 0.0167,
          inclinationDeg: 0.0,
          longitudeOfPeriapsisDeg: 102.94,
          subsolarLongitudeDeg: 0.0,
          rotationPeriodHours: 23.934,
          axialTiltDeg: 23.44,
          massEarth: 1.0,
          cmfPct: 33.3,
          wmfPct: 0.1,
          albedoBond: 0.306,
          greenhouseEffect: 1.19,
          greenhouseMode: "core",
          observerHeightM: 1.75,
          pressureAtm: 1.0,
          o2Pct: 20.95,
          co2Pct: 0.04,
          arPct: 0.93,
          h2oPct: 0.4,
          ch4Pct: 0.00018,
          h2Pct: 0,
          hePct: 0,
          so2Pct: 0,
          nh3Pct: 0,
          tectonicRegime: "auto",
          mantleOxidation: "earth",
        },
      },
      p_mars: {
        id: "p_mars",
        name: "Mars",
        slotIndex: null,
        locked: false,
        inputs: {
          name: "Mars",
          semiMajorAxisAu: 1.5237,
          eccentricity: 0.0935,
          inclinationDeg: 1.85,
          longitudeOfPeriapsisDeg: 336.04,
          subsolarLongitudeDeg: 0.0,
          rotationPeriodHours: 24.623,
          axialTiltDeg: 25.19,
          massEarth: 0.107,
          cmfPct: 24.0,
          wmfPct: 0,
          albedoBond: 0.25,
          greenhouseEffect: 0.05,
          greenhouseMode: "core",
          observerHeightM: 1.75,
          pressureAtm: 0.006,
          o2Pct: 0.13,
          co2Pct: 95.32,
          arPct: 1.6,
          h2oPct: 0.03,
          ch4Pct: 0,
          h2Pct: 0,
          hePct: 0,
          so2Pct: 0,
          nh3Pct: 0,
          tectonicRegime: "stagnant",
          mantleOxidation: "earth",
        },
      },
      p_ceres: {
        id: "p_ceres",
        name: "Ceres",
        slotIndex: null,
        locked: false,
        inputs: {
          name: "Ceres",
          semiMajorAxisAu: 2.7675,
          eccentricity: 0.0758,
          inclinationDeg: 10.59,
          longitudeOfPeriapsisDeg: 73.6,
          subsolarLongitudeDeg: 0.0,
          rotationPeriodHours: 9.074,
          axialTiltDeg: 4.0,
          massEarth: 0.00016,
          cmfPct: 25.0,
          wmfPct: 25.0,
          albedoBond: 0.034,
          greenhouseEffect: 0.0,
          greenhouseMode: "core",
          observerHeightM: 1.75,
          pressureAtm: 0.0,
          o2Pct: 0.0,
          co2Pct: 0.0,
          arPct: 0.0,
          h2oPct: 0,
          ch4Pct: 0,
          h2Pct: 0,
          hePct: 0,
          so2Pct: 0,
          nh3Pct: 0,
          tectonicRegime: "stagnant",
          mantleOxidation: "earth",
        },
      },
      p_pluto: {
        id: "p_pluto",
        name: "Pluto",
        slotIndex: null,
        locked: false,
        inputs: {
          name: "Pluto",
          semiMajorAxisAu: 39.482,
          eccentricity: 0.2488,
          inclinationDeg: 17.16,
          longitudeOfPeriapsisDeg: 113.83,
          subsolarLongitudeDeg: 0.0,
          rotationPeriodHours: 153.29,
          axialTiltDeg: 122.53,
          massEarth: 0.0022,
          cmfPct: 32.0,
          wmfPct: 30.0,
          albedoBond: 0.72,
          greenhouseEffect: 0.0,
          greenhouseMode: "core",
          observerHeightM: 1.75,
          pressureAtm: 0.00001,
          o2Pct: 0.0,
          co2Pct: 0.0,
          arPct: 0.0,
          h2oPct: 0,
          ch4Pct: 5.0,
          h2Pct: 0,
          hePct: 0,
          so2Pct: 0,
          nh3Pct: 0,
          tectonicRegime: "stagnant",
          mantleOxidation: "earth",
        },
      },
    },
  },
  moons: {
    selectedId: "m_luna",
    order: [
      "m_luna",
      "m_phobos",
      "m_deimos",
      "m_io",
      "m_europa",
      "m_ganymede",
      "m_callisto",
      "m_mimas",
      "m_enceladus",
      "m_tethys",
      "m_dione",
      "m_rhea",
      "m_titan",
      "m_iapetus",
      "m_miranda",
      "m_ariel",
      "m_umbriel",
      "m_titania",
      "m_oberon",
      "m_triton",
      "m_proteus",
      "m_nereid",
      "m_charon",
    ],
    byId: {
      /* ── Earth ───────────────────────────────────────── */
      m_luna: {
        id: "m_luna",
        name: "Moon",
        planetId: "p_earth",
        locked: false,
        inputs: {
          name: "Moon",
          semiMajorAxisKm: 384400,
          eccentricity: 0.0549,
          inclinationDeg: 5.145,
          massMoon: 1.0,
          densityGcm3: 3.34,
          albedo: 0.11,
          compositionOverride: null,
        },
      },
      /* ── Mars ────────────────────────────────────────── */
      m_phobos: {
        id: "m_phobos",
        name: "Phobos",
        planetId: "p_mars",
        locked: false,
        inputs: {
          name: "Phobos",
          semiMajorAxisKm: 9375,
          eccentricity: 0.015,
          inclinationDeg: 1.09,
          massMoon: 0.000000145,
          densityGcm3: 1.876,
          albedo: 0.071,
          compositionOverride: null,
        },
      },
      m_deimos: {
        id: "m_deimos",
        name: "Deimos",
        planetId: "p_mars",
        locked: false,
        inputs: {
          name: "Deimos",
          semiMajorAxisKm: 23457,
          eccentricity: 0.0002,
          inclinationDeg: 0.93,
          massMoon: 0.00000002,
          densityGcm3: 1.47,
          albedo: 0.068,
          compositionOverride: null,
        },
      },
      /* ── Jupiter (Galilean moons) ────────────────────── */
      m_io: {
        id: "m_io",
        name: "Io",
        planetId: "gg_jupiter",
        locked: false,
        inputs: {
          name: "Io",
          semiMajorAxisKm: 421800,
          eccentricity: 0.0041,
          inclinationDeg: 0.036,
          massMoon: 1.215,
          densityGcm3: 3.528,
          albedo: 0.63,
          compositionOverride: null,
        },
      },
      m_europa: {
        id: "m_europa",
        name: "Europa",
        planetId: "gg_jupiter",
        locked: false,
        inputs: {
          name: "Europa",
          semiMajorAxisKm: 671100,
          eccentricity: 0.0094,
          inclinationDeg: 0.466,
          massMoon: 0.654,
          densityGcm3: 3.013,
          albedo: 0.67,
          compositionOverride: null,
        },
      },
      m_ganymede: {
        id: "m_ganymede",
        name: "Ganymede",
        planetId: "gg_jupiter",
        locked: false,
        inputs: {
          name: "Ganymede",
          semiMajorAxisKm: 1070400,
          eccentricity: 0.0011,
          inclinationDeg: 0.177,
          massMoon: 2.017,
          densityGcm3: 1.942,
          albedo: 0.43,
          compositionOverride: null,
        },
      },
      m_callisto: {
        id: "m_callisto",
        name: "Callisto",
        planetId: "gg_jupiter",
        locked: false,
        inputs: {
          name: "Callisto",
          semiMajorAxisKm: 1882700,
          eccentricity: 0.0074,
          inclinationDeg: 0.192,
          massMoon: 1.466,
          densityGcm3: 1.834,
          albedo: 0.17,
          compositionOverride: null,
        },
      },
      /* ── Saturn ──────────────────────────────────────── */
      m_mimas: {
        id: "m_mimas",
        name: "Mimas",
        planetId: "gg_saturn",
        locked: false,
        inputs: {
          name: "Mimas",
          semiMajorAxisKm: 185540,
          eccentricity: 0.02,
          inclinationDeg: 1.57,
          massMoon: 0.000511,
          densityGcm3: 1.149,
          albedo: 0.962,
          compositionOverride: null,
        },
      },
      m_enceladus: {
        id: "m_enceladus",
        name: "Enceladus",
        planetId: "gg_saturn",
        locked: false,
        inputs: {
          name: "Enceladus",
          semiMajorAxisKm: 238400,
          eccentricity: 0.0047,
          inclinationDeg: 0.009,
          massMoon: 0.001471,
          densityGcm3: 1.61,
          albedo: 1.375,
          compositionOverride: null,
        },
      },
      m_tethys: {
        id: "m_tethys",
        name: "Tethys",
        planetId: "gg_saturn",
        locked: false,
        inputs: {
          name: "Tethys",
          semiMajorAxisKm: 294670,
          eccentricity: 0.0001,
          inclinationDeg: 1.09,
          massMoon: 0.008411,
          densityGcm3: 0.984,
          albedo: 1.229,
          compositionOverride: null,
        },
      },
      m_dione: {
        id: "m_dione",
        name: "Dione",
        planetId: "gg_saturn",
        locked: false,
        inputs: {
          name: "Dione",
          semiMajorAxisKm: 377420,
          eccentricity: 0.002,
          inclinationDeg: 0.03,
          massMoon: 0.01492,
          densityGcm3: 1.476,
          albedo: 0.998,
          compositionOverride: null,
        },
      },
      m_rhea: {
        id: "m_rhea",
        name: "Rhea",
        planetId: "gg_saturn",
        locked: false,
        inputs: {
          name: "Rhea",
          semiMajorAxisKm: 527070,
          eccentricity: 0.001,
          inclinationDeg: 0.33,
          massMoon: 0.03142,
          densityGcm3: 1.233,
          albedo: 0.949,
          compositionOverride: null,
        },
      },
      m_titan: {
        id: "m_titan",
        name: "Titan",
        planetId: "gg_saturn",
        locked: false,
        inputs: {
          name: "Titan",
          semiMajorAxisKm: 1221870,
          eccentricity: 0.0288,
          inclinationDeg: 0.306,
          massMoon: 1.8324,
          densityGcm3: 1.882,
          albedo: 0.21,
          compositionOverride: null,
        },
      },
      m_iapetus: {
        id: "m_iapetus",
        name: "Iapetus",
        planetId: "gg_saturn",
        locked: false,
        inputs: {
          name: "Iapetus",
          semiMajorAxisKm: 3560840,
          eccentricity: 0.0276,
          inclinationDeg: 15.47,
          massMoon: 0.02459,
          densityGcm3: 1.088,
          albedo: 0.22,
          compositionOverride: null,
        },
      },
      /* ── Uranus ──────────────────────────────────────── */
      m_miranda: {
        id: "m_miranda",
        name: "Miranda",
        planetId: "gg_uranus",
        locked: false,
        inputs: {
          name: "Miranda",
          semiMajorAxisKm: 129390,
          eccentricity: 0.0013,
          inclinationDeg: 4.232,
          massMoon: 0.0009,
          densityGcm3: 1.2,
          albedo: 0.32,
          compositionOverride: null,
        },
      },
      m_ariel: {
        id: "m_ariel",
        name: "Ariel",
        planetId: "gg_uranus",
        locked: false,
        inputs: {
          name: "Ariel",
          semiMajorAxisKm: 190900,
          eccentricity: 0.0012,
          inclinationDeg: 0.26,
          massMoon: 0.0184,
          densityGcm3: 1.66,
          albedo: 0.39,
          compositionOverride: null,
        },
      },
      m_umbriel: {
        id: "m_umbriel",
        name: "Umbriel",
        planetId: "gg_uranus",
        locked: false,
        inputs: {
          name: "Umbriel",
          semiMajorAxisKm: 266000,
          eccentricity: 0.0039,
          inclinationDeg: 0.205,
          massMoon: 0.0162,
          densityGcm3: 1.39,
          albedo: 0.21,
          compositionOverride: null,
        },
      },
      m_titania: {
        id: "m_titania",
        name: "Titania",
        planetId: "gg_uranus",
        locked: false,
        inputs: {
          name: "Titania",
          semiMajorAxisKm: 435910,
          eccentricity: 0.0011,
          inclinationDeg: 0.34,
          massMoon: 0.048,
          densityGcm3: 1.71,
          albedo: 0.35,
          compositionOverride: null,
        },
      },
      m_oberon: {
        id: "m_oberon",
        name: "Oberon",
        planetId: "gg_uranus",
        locked: false,
        inputs: {
          name: "Oberon",
          semiMajorAxisKm: 583520,
          eccentricity: 0.0014,
          inclinationDeg: 0.058,
          massMoon: 0.0411,
          densityGcm3: 1.63,
          albedo: 0.31,
          compositionOverride: null,
        },
      },
      /* ── Neptune ─────────────────────────────────────── */
      m_triton: {
        id: "m_triton",
        name: "Triton",
        planetId: "gg_neptune",
        locked: false,
        inputs: {
          name: "Triton",
          semiMajorAxisKm: 354800,
          eccentricity: 0.000016,
          inclinationDeg: 157.345,
          massMoon: 0.2913,
          densityGcm3: 2.065,
          albedo: 0.7,
          compositionOverride: null,
        },
      },
      m_proteus: {
        id: "m_proteus",
        name: "Proteus",
        planetId: "gg_neptune",
        locked: false,
        inputs: {
          name: "Proteus",
          semiMajorAxisKm: 117647,
          eccentricity: 0.00053,
          inclinationDeg: 0.524,
          massMoon: 0.0006,
          densityGcm3: 1.3,
          albedo: 0.096,
          compositionOverride: null,
        },
      },
      m_nereid: {
        id: "m_nereid",
        name: "Nereid",
        planetId: "gg_neptune",
        locked: false,
        inputs: {
          name: "Nereid",
          semiMajorAxisKm: 5513400,
          eccentricity: 0.7507,
          inclinationDeg: 28.6,
          massMoon: 0.00042,
          densityGcm3: 1.5,
          albedo: 0.155,
          compositionOverride: null,
        },
      },
      /* ── Pluto ──────────────────────────────────────── */
      m_charon: {
        id: "m_charon",
        name: "Charon",
        planetId: "p_pluto",
        locked: false,
        inputs: {
          name: "Charon",
          semiMajorAxisKm: 19591,
          eccentricity: 0.0002,
          inclinationDeg: 0.08,
          massMoon: 0.0218,
          densityGcm3: 1.702,
          albedo: 0.2,
          compositionOverride: null,
        },
      },
    },
  },
  calendar: {
    activeProfileId: "cal-gregorian-uk",
    profiles: [
      {
        id: "cal-gregorian-uk",
        name: "Gregorian (UK)",
        inputs: {
          sourcePlanetId: "p_earth",
          primaryMoonId: "m_luna",
          extraMoonIds: ["", "", ""],
          monthsPerYear: 12,
          solarWeeksPerMonth: 4,
          lunarWeeksPerMonth: 4,
          lunisolarWeeksPerMonth: 4,
        },
        ui: {
          calendarName: "Gregorian (UK)",
          basis: "solar",
          year: 2026,
          monthIndex: 0,
          selectedDay: 1,
          startDayOfYear: 0,
          weekStartsOn: 0,
          moonEpochOffsetDays: 0,
          dayNames: GREGORIAN_DAY_NAMES,
          weekNames: [],
          monthNames: GREGORIAN_MONTH_NAMES,
          yearDisplayMode: "pre-calendar",
          yearOffset: 0,
          yearPrefix: "",
          yearSuffix: "",
          preCalendarStartYear: 1,
          postEraLabel: "CE",
          preEraLabel: "BCE",
          preCalendarUseYearZero: false,
          eras: [],
          astronomy: {
            enabled: false,
            seasons: true,
            seasonBands: true,
            eclipses: true,
          },
          exportAnchorDate: "2026-01-01",
          icsIncludes: {
            holidays: true,
            festivals: true,
            markers: true,
          },
          leapRules: GREGORIAN_LEAP_RULES,
          holidays: UK_HOLIDAY_RULES,
          festivalRules: [],
          holidayCategoryFilters: {
            civic: true,
            religious: true,
            regional: true,
            market: true,
            observance: true,
            custom: true,
          },
          workCycles: [],
          jumpAbsoluteDay: 0,
          jumpYear: 2026,
          jumpMonthIndex: 0,
          jumpDayOfMonth: 1,
          collapsedSections: {
            designer: true,
            data: true,
            output: true,
            special: true,
            festival: true,
            leap: true,
            cycles: true,
          },
        },
      },
    ],
  },
  cluster: {
    galacticRadiusLy: 50000,
    locationLy: 25800,
    neighbourhoodRadiusLy: 10,
    stellarDensityPerLy3: 0.004,
    randomSeed: 1,
  },
  clusterSystemNames: {},
  clusterAdjustments: {
    addedSystems: [],
    removedSystemIds: [],
    componentOverrides: {},
  },
};

function deepClone(value) {
  return JSON.parse(JSON.stringify(value));
}

export function createSolPresetEnvelope() {
  return { world: deepClone(SOL_PRESET_WORLD) };
}
